- name: "apache installation using docker"

  hosts: prod

  become: true

  vars:

  pre_tasks:
    - name: install Epel repo
      package:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"
    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
      changed_when: false
    - name: Install docker python
      pip: name=docker-py

  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: Create Apache Conteneur
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
